/*
Star schema for the 2023 data job postings dataset.

Grain
    job_postings_fact : one row per job posting
    company_dim       : one row per company
    skills_dim        : one row per skill
    skills_job_dim    : one row per posting/skill pair (bridge)

Portability
    Valid in both DuckDB and PostgreSQL. Surrogate keys are generated by
    scripts/build_database.py because the published source file is denormalised
    and carries no keys of its own.
*/

DROP TABLE IF EXISTS skills_job_dim;
DROP TABLE IF EXISTS job_postings_fact;
DROP TABLE IF EXISTS skills_dim;
DROP TABLE IF EXISTS company_dim;

CREATE TABLE company_dim (
    company_id INTEGER PRIMARY KEY,
    name       TEXT NOT NULL
);

CREATE TABLE skills_dim (
    skill_id INTEGER PRIMARY KEY,
    skills   TEXT NOT NULL
);

CREATE TABLE job_postings_fact (
    job_id                INTEGER PRIMARY KEY,
    company_id            INTEGER NOT NULL REFERENCES company_dim (company_id),
    job_title_short       VARCHAR(255),
    job_title             TEXT,
    job_location          TEXT,
    job_via               TEXT,
    job_schedule_type     TEXT,
    job_work_from_home    BOOLEAN,
    search_location       TEXT,
    job_posted_date       TIMESTAMP,
    job_no_degree_mention BOOLEAN,
    job_health_insurance  BOOLEAN,
    job_country           TEXT,
    salary_rate           TEXT,
    salary_year_avg       DECIMAL(12, 2),
    salary_hour_avg       DECIMAL(10, 2)
);

CREATE TABLE skills_job_dim (
    job_id   INTEGER NOT NULL REFERENCES job_postings_fact (job_id),
    skill_id INTEGER NOT NULL REFERENCES skills_dim (skill_id),
    PRIMARY KEY (job_id, skill_id)
);

CREATE INDEX idx_postings_title_short ON job_postings_fact (job_title_short);
CREATE INDEX idx_postings_company_id  ON job_postings_fact (company_id);
CREATE INDEX idx_skills_job_skill_id  ON skills_job_dim (skill_id);
